apiVersion: apps/v1
kind: Deployment
metadata:
  name: PROJECT_NAME_WITH_DASH-mac-app
  labels:
    app: PROJECT_NAME_WITH_DASH-mac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PROJECT_NAME_WITH_DASH-mac
  template:
    metadata:
      labels:
        app: PROJECT_NAME_WITH_DASH-mac
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - image: DOCKER_REGISTRY/DOCKER_REPOSITORY/DOCKER_IMAGE_NAME_mac:latest
          name: PROJECT_NAME_WITH_DASH-mac
          envFrom:
            - secretRef:
                name: PROJECT_NAME_WITH_DASH-secret
          ports:
            - containerPort: DOCKER_PORT
              name: gunicorn
  revisionHistoryLimit: 0